import {
  Brain, Users, Sparkles, List, Layers, BookOpen, Heart, Star, Zap, Target, Clock, Globe, Settings,
  Home, Search, Mail, Phone, Camera, Music, Video, Image, File, Folder, Download, Upload,
  Edit, Trash2, Save, Share, Lock, Unlock, Eye, EyeOff, Plus, Minus, Check, X,
} from "lucide-react";

export const ICON_OPTIONS = [
  { value: "list", icon: List, label: "List" },
  { value: "brain", icon: Brain, label: "Brain" },
  { value: "users", icon: Users, label: "Users" },
  { value: "sparkles", icon: Sparkles, label: "Sparkles" },
  { value: "layers", icon: Layers, label: "Layers" },
  { value: "book", icon: BookOpen, label: "Book" },
  { value: "heart", icon: Heart, label: "Heart" },
  { value: "star", icon: Star, label: "Star" },
  { value: "zap", icon: Zap, label: "Zap" },
  { value: "target", icon: Target, label: "Target" },
  { value: "clock", icon: Clock, label: "Clock" },
  { value: "globe", icon: Globe, label: "Globe" },
  { value: "settings", icon: Settings, label: "Settings" },
  { value: "home", icon: Home, label: "Home" },
  { value: "search", icon: Search, label: "Search" },
  { value: "mail", icon: Mail, label: "Mail" },
  { value: "phone", icon: Phone, label: "Phone" },
  { value: "camera", icon: Camera, label: "Camera" },
  { value: "music", icon: Music, label: "Music" },
  { value: "video", icon: Video, label: "Video" },
  { value: "image", icon: Image, label: "Image" },
  { value: "file", icon: File, label: "File" },
  { value: "folder", icon: Folder, label: "Folder" },
  { value: "download", icon: Download, label: "Download" },
  { value: "upload", icon: Upload, label: "Upload" },
  { value: "edit", icon: Edit, label: "Edit" },
  { value: "trash", icon: Trash2, label: "Trash" },
  { value: "save", icon: Save, label: "Save" },
  { value: "share", icon: Share, label: "Share" },
  { value: "lock", icon: Lock, label: "Lock" },
  { value: "unlock", icon: Unlock, label: "Unlock" },
  { value: "eye", icon: Eye, label: "Eye" },
  { value: "eye-off", icon: EyeOff, label: "Eye Off" },
  { value: "plus", icon: Plus, label: "Plus" },
  { value: "minus", icon: Minus, label: "Minus" },
  { value: "check", icon: Check, label: "Check" },
  { value: "x", icon: X, label: "X" },
];

export const iconMap: Record<string, React.ElementType> = {
  brain: Brain,
  users: Users,
  sparkles: Sparkles,
  list: List,
  layers: Layers,
  book: BookOpen,
  heart: Heart,
  star: Star,
  zap: Zap,
  target: Target,
  clock: Clock,
  globe: Globe,
  settings: Settings,
  home: Home,
  search: Search,
  mail: Mail,
  phone: Phone,
  camera: Camera,
  music: Music,
  video: Video,
  image: Image,
  file: File,
  folder: Folder,
  download: Download,
  upload: Upload,
  edit: Edit,
  trash: Trash2,
  save: Save,
  share: Share,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  "eye-off": EyeOff,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
};