import {
  Archive,
  Book,
  Bookmark,
  Briefcase,
  Camera,
  Clapperboard,
  Code,
  Coffee,
  Compass,
  Gamepad2,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Lightbulb,
  List,
  type LucideIcon,
  Music,
  Newspaper,
  Palette,
  Rocket,
  ShoppingCart,
  Sparkles,
  Star,
  Utensils,
  Wrench,
} from "lucide-react";

export const LIST_ICONS: Record<string, LucideIcon> = {
  list: List,
  bookmark: Bookmark,
  book: Book,
  archive: Archive,
  briefcase: Briefcase,
  camera: Camera,
  clapperboard: Clapperboard,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  gamepad: Gamepad2,
  globe: Globe,
  "graduation-cap": GraduationCap,
  heart: Heart,
  home: Home,
  lightbulb: Lightbulb,
  music: Music,
  newspaper: Newspaper,
  palette: Palette,
  rocket: Rocket,
  "shopping-cart": ShoppingCart,
  sparkles: Sparkles,
  star: Star,
  utensils: Utensils,
  wrench: Wrench,
};

export function getListIcon(name?: string | null): LucideIcon {
  if (!name) return List;
  return LIST_ICONS[name.toLowerCase()] ?? List;
}
